### ISSUE TITLE
Ability to Customize Browser Versions

### ISSUE THREAD

**Issue by osdevisnot** [kitten/tiny-css-prefixer#3]
Currently we are at ~ 304 B (min + gzip), and I am wondering how much lower we can go if we drop IE11 support.

If it reduces size by at least say 20%, maybe we can produce 2 builds, one with IE11 prefixes and other without.

It seems inline-style-prefixer let's us customize the browser versions by creating Custom Prefixer.

**Comment by kitten** [comment]
I’ll check this; this could in theory be exposed as `/modern` and all that’d need to be done is to omit the logic and regex for `-ms-` prefixes.
I doubt it’ll make a large difference right now though, especially since the size is already quite low

**Comment by kitten** [comment]
I don't think this is worth doing. Leaving out the `-ms-` prefixes only saves a couple of bytes (`304kB` -> `289kB` gzip)
